# Generated by Django 3.1.7 on 2022-04-06 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='blog'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='contend',
            field=models.TextField(blank=True, verbose_name='contenu'),
        ),
    ]
